FROM  node:lts-alpine as builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:lts-alpine as runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./.next
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./
EXPOSE 3000
CMD ["node", ".next/server.js"]