FROM python:3.12-slim
WORKDIR /app
COPY requirement.txt /app/requirement.txt
RUN pip install --no-cache-dir -r /app/requirement.txt
COPY backend/ /app/backend/
COPY db/ /app/db/
COPY utils/ /app/utils/
EXPOSE 8000
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]